version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: team
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: students
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node_app:
    build:
      dockerfile: Dockerfile
    container_name: node_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
